version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: daphne manage_restaurant_api.asgi:application
    volumes: 
      - ./manage_restaurant_api:/app/
    ports:
      - 8000:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - SECRET_KEY
      - EMAIL_HOST_USER 
      - EMAIL_HOST_PASSWORD
      - TWILIO_PHONENUMBER
      - TWILIO_SID
      - TWILIO_TOKEN
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - redis

  celery:
    container_name: celery_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: celery --app=manage_restaurant_api worker -l INFO
    volumes: 
      - ./manage_restaurant_api:/app/
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - SECRET_KEY
      - EMAIL_HOST_USER 
      - EMAIL_HOST_PASSWORD
      - TWILIO_PHONENUMBER
      - TWILIO_SID
      - TWILIO_TOKEN
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT

    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    depends_on:
      - db
    ports:
      - 6432:6432
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POOL_MODE: session
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20

volumes:
  pgdata: