version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./manage_restaurant_api:/app/
    ports:
      - 8000:8000
    env_file:
      - manage_restaurant_api/.env
    depends_on:
      - redis

  celery:
    container_name: celery_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: celery --app=manage_restaurant_api worker -l INFO
    volumes: 
      - ./manage_restaurant_api:/app/
    env_file:
      - manage_restaurant_api/.env
    depends_on:
      - redis

