version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: daphne manage_restaurant_api.asgi:application
    volumes: 
      - ./manage_restaurant_api:/app/
    ports:
      - 8001:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - SECRET_KEY
      - EMAIL_HOST_USER 
      - EMAIL_HOST_PASSWORD
      - TWILIO_PHONENUMBER
      - TWILIO_SID
      - TWILIO_TOKEN
    depends_on:
      - redis

  celery:
    container_name: celery_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: celery --app=manage_restaurant_api worker -l INFO
    volumes: 
      - ./manage_restaurant_api:/app/
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - SECRET_KEY
      - EMAIL_HOST_USER 
      - EMAIL_HOST_PASSWORD
      - TWILIO_PHONENUMBER
      - TWILIO_SID
      - TWILIO_TOKEN
    depends_on:
      - redis