services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: daphne -b 0.0.0.0 -p 8000 manage_restaurant_api.asgi:application
    volumes: 
      - ./manage_restaurant_api:/app/
    ports:
      - 8000:8000
    env_file:
      - manage_restaurant_api/.env
    depends_on:
      - redis
      - pgbouncer

  celery:
    container_name: celery_manage_restaurant
    build:
      context: ./manage_restaurant_api
    command: celery --app=manage_restaurant_api worker -l INFO
    volumes: 
      - ./manage_restaurant_api:/app/
    env_file:
      - manage_restaurant_api/.env
    depends_on:
      - redis

  db:
    image: postgres:15
    env_file:
      - manage_restaurant_api/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    depends_on:
      - db
    ports:
      - 6432:6432
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POOL_MODE: session
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20

volumes:
  pgdata: