# Generated by Django 5.2.4 on 2025-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="category",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("DELIVER", "Deliver"),
                    ("KITCHENMANAGER", "Kitchen_manager"),
                    ("WAITER", "Waiter"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
