# Generated by Django 5.2.4 on 2025-07-17 13:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(default="3841", max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="short_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
    ]
