version: 2.1


jobs:
  run_tests:
  
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: docker-compose -f docker-compose.override.yml up -d --build


workflows:
  version: 2
  test_workflow:
    jobs:
      - run_tests